### ISSUE TITLE
video camera in portrait mode

### ISSUE THREAD

**Issue by techadroit** [JeroenMols/LandscapeVideoCamera#12]
Hi JeorenMols,

How do I make this library  work in portrait mode as well as with the feature of adjusting the resolution ?

**Comment by JeroenMols** [comment]
Hi @techadroit 

Very good question. All library components are agnostic about the devices orientation, so you will be able to reuse everything but the topmost VideoCaptureActivity.

You will need to create your own Activity which integrates both a VideoRecorder and VideoCaptureView. Then set a layout to that activity which includes the VideoCaptureView in both portrait and landscape mode. Note that if you want to allow users to rotate their device whilst filming, you will need to handle the camera orientation yourself in the manifest.

Have a look at the [VideoCaptureActivity](https://github.com/JeroenMols/LandscapeVideoCamera/blob/master/library/src/main/java/com/jmolsmobile/landscapevideocapture/VideoCaptureActivity.java) there everything is explained on how to integrate the VideoRecorder and VideoCaptureView.

If you're done with your implementation, feel free to issue a pull request!

Good luck!
Jeroen

**Comment by techadroit** [comment]
Thanks Jeroen for the reply, I will try it out.

**Comment by rahulraj64** [comment]
I have a similar requirement. Did anyone implement a portrait version of the library?
