### ISSUE TITLE
Not correctly working on Nexus 5x

### ISSUE THREAD

**Issue by Laeyoung** [JeroenMols/LandscapeVideoCamera#14]
![nexus5x](https://cloud.githubusercontent.com/assets/1391299/11175051/004dd7d2-8c71-11e5-9db7-a48a28a33786.jpg)

Video preview and result are rotated 180 degree on Nexus 5x.

**Comment by JeroenMols** [comment]
Found an interesting article explaining this issue: http://www.androidheadlines.com/2015/11/upside-camera-preview-nexus-5x-explained.html

I'll try to provide a fix on a new branch and keep you posted.

**Comment by JeroenMols** [comment]
Made a quick and dirty fix so you can verify if this idea is working.
You can find the apk here: https://drive.google.com/file/d/0B_3yQOBMz3jvVlNiTXByeWlpblU/view?usp=sharing
@Laeyoung Can you please test and let me know if it is working or not?

If this does the trick, I'll properly implement it and integrate it back into the main branch.

**Comment by Laeyoung** [comment]
@JeroenMols Unfortunatelly, It was working same as before. Thank you for helping me.

I am trying to fix this issue. If I fix it, I will make a pull request on the main branch.

**Comment by JeroenMols** [comment]
@Laeyoung You are very welcome!
I've pushed my quick and dirty fix to a branch so you can see what I've alread tried: https://github.com/JeroenMols/LandscapeVideoCamera/tree/issue%2314-quickanddirtyfix

**Comment by JeroenMols** [comment]
Hi @Laeyoung ,

I want to avoid making device specific fixes, as that would generate a maintenance mess. Therefore I attempted a second fix (same pull request). Could you verify if this APK is working for you? https://drive.google.com/file/d/0B_3yQOBMz3jvYnVnYzA0eDA1a2M/view?usp=sharing

Many thanks,
Jeroen

**Comment by Laeyoung** [comment]
Hi @JeroenMols 

I tested your apk on Nexus 5X and Nexus 6. It worked well!

I made a device specific fix because I didn't have enough time at last week. I think your code is better : )

**Comment by JeroenMols** [comment]
Hi @Laeyoung ,

I've integrated the changes discussed above into the main brand and created a new release:
https://github.com/JeroenMols/LandscapeVideoCamera/releases/tag/1.1.3

Can you please test to see if it is working? (there is also a new play store app)

Thanks,
Jeroen

**Comment by Laeyoung** [comment]
I installed and tested play store app version on my Nexus 5x and Nexus 6. It was working well on landscape and reverse landscape.

@JeroenMols 
Thank you to fix this rapidly!

**Comment by JeroenMols** [comment]
Great! Thanks for reporting. :)
