### ISSUE TITLE
java.lang.RuntimeException: setAudioSource failed.

### ISSUE THREAD

**Issue by mohittanwar94** [JeroenMols/LandscapeVideoCamera#23]
setAudioSource failed.

**Comment by JeroenMols** [comment]
Can you provide more information?
Like a full stack trace, detailed exception and device you are using and CaptureConfiguration.

**Comment by mohittanwar94** [comment]
Hii Jeroen ,

its working now. that was my mistake.capture configuration was wrong set.

**Comment by JeroenMols** [comment]
Great to hear!
