### ISSUE TITLE
On Android 6.0 camera does not start

### ISSUE THREAD

**Issue by a785436663** [JeroenMols/LandscapeVideoCamera#25]
Android4.4.2，It runs normally.
on Android6.0 ，Exception:Camera disabled or in use by other process

Here is the log：
 W/System.err: java.lang.RuntimeException: Fail to connect to camera service
 W/System.err:     at android.hardware.Camera.<init>(Camera.java:542)
 W/System.err:     at android.hardware.Camera.open(Camera.java:397)
 W/System.err:     at com.jmolsmobile.landscapevideocapture.camera.NativeCamera.openNativeCamera(NativeCamera.java:27)
 W/System.err:     at com.jmolsmobile.landscapevideocapture.camera.CameraWrapper.openCamera(CameraWrapper.java:54)
 W/System.err:     at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.initializeCameraAndPreview(VideoRecorder.java:63)
 W/System.err:     at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.<init>(VideoRecorder.java:58)
 W/System.err:     at com.jmolsmobile.landscapevideocapture.VideoCaptureActivity.initializeRecordingUI(VideoCaptureActivity.java:83)
 W/System.err:     at com.jmolsmobile.landscapevideocapture.VideoCaptureActivity.onCreate(VideoCaptureActivity.java:71)
 W/System.err:     at android.app.Activity.performCreate(Activity.java:6303)
 W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
 W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2374)
 W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
 W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:153)
 W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
 W/System.err:     at android.os.Looper.loop(Looper.java:148)
 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5432)
 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
 E/VideoCapture_Exception: Unable to open camera - Camera disabled or in use by other process
 W/System.err: com.jmolsmobile.landscapevideocapture.camera.OpenCameraException: Camera disabled or in use by other process
 W/System.err:     at com.jmolsmobile.landscapevideocapture.camera.CameraWrapper.openCamera(CameraWrapper.java:57)
 W/System.err:     at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.initializeCameraAndPreview(VideoRecorder.java:63)
 W/System.err:     at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.<init>(VideoRecorder.java:58)
 W/System.err:     at com.jmolsmobile.landscapevideocapture.VideoCaptureActivity.initializeRecordingUI(VideoCaptureActivity.java:83)
 W/System.err:     at com.jmolsmobile.landscapevideocapture.VideoCaptureActivity.onCreate(VideoCaptureActivity.java:71)
 W/System.err:     at android.app.Activity.performCreate(Activity.java:6303)
 W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
 W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2374)
 W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
 W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:153)
 W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
 W/System.err:     at android.os.Looper.loop(Looper.java:148)
 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5432)
 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)

**Comment by a785436663** [comment]
I have found the cause of the problem,
android6.0 need request Permission.

**Comment by JeroenMols** [comment]
Great to hear!

**Comment by flyou** [comment]
if user did't give the permission of 
   <uses-permission android:name="android.permission.RECORD_AUDIO" />

the camera can prew but can not record video 
when i open the camera  will appear can not connect the camear service

**Comment by rennovale** [comment]
Can somebody tell me how request permission for the activity? Because i'm asking and nothing changes. The "request" popup appears, i'm accepting and same "Camera in use" message appears.

Basically i'm using this in my MainActivity 

`ActivityCompat.requestPermissions(MainActivity.this, new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, STORAGE_PERMISSION_CODE);
`
The MainActivity call the recordvideo() method after checking if the permission was conceded 

```
final Intent intent = new Intent(this, VideoCaptureActivity.class);
            intent.putExtra(VideoCaptureActivity.EXTRA_CAPTURE_CONFIGURATION, configuration);
            intent.putExtra(VideoCaptureActivity.EXTRA_OUTPUT_FILENAME, videoUri);
            startActivityForResult(intent, REQUEST_VIDEO_CAPTURE);
```

I was having this trouble with the android default service to record videos, but my permission fixed the problem.
