### ISSUE TITLE
Photographed with the front camera, there are stripes

### ISSUE THREAD

**Issue by smuyyh** [JeroenMols/LandscapeVideoCamera#28]
Use CameraInfo.CAMERA_FACING_FRONT On SamSung-note2.Just like that，when the recording is complete.
![http://oaa9buxqy.bkt.clouddn.com/device-2016-07-27-224125.png](http://oaa9buxqy.bkt.clouddn.com/device-2016-07-27-224125.png)

**Comment by JeroenMols** [comment]
Front camera is currently not supported, hence rejecting this issue.
