### ISSUE TITLE
Gradle import issue

### ISSUE THREAD

**Issue by tanuja05** [JeroenMols/LandscapeVideoCamera#31]
I was trying to access the library from gradle , it always showing me the message:-

Error:(139, 13) Failed to resolve: com.github.JeroenMols:LandscapeVideoCamera:1.1.4

 Can you please explain why this is happening.

**Comment by JeroenMols** [comment]
Not a technical issue with the library.
Suggest to follow instructions on how to integrate and have a look at the example.
