### ISSUE TITLE
click start button crashed

### ISSUE THREAD

**Issue by Cwj1992** [JeroenMols/LandscapeVideoCamera#33]
![image](https://cloud.githubusercontent.com/assets/17961271/18038739/516a8888-6dce-11e6-9f82-0f9a928b1486.png)
OS:Android 6.0  
phone: mi6

**Comment by JeroenMols** [comment]
@Cwj1992 I don't have a mi6 phone to reproduce and your stack trace is too short to make sense of. Have you already been able to find a solution in the mean while?

**Comment by kevalpatel2106** [comment]
@Cwj1992 Are you sure you provided microphone permissions (android.permission.RECORD_AUDIO) in runtime?

**Comment by JeroenMols** [comment]
Closing as no answer from the reporter
