### ISSUE TITLE
May I know what the below script does in your travis-ci yml file

### ISSUE THREAD

**Issue by bhargavms** [JeroenMols/LandscapeVideoCamera#39]
before_install:
  - pip install --user codecov
  
after_success:
  - codecov

**Comment by JeroenMols** [comment]
Codecov is an external service that creates nice visualisations of code coverage.
Both of those are required to make that work together with Travis CI.

This is the commit where I added it: https://github.com/JeroenMols/LandscapeVideoCamera/commit/1fcd47ce9accfb15a614f87e49f9436f1ddfbc43

To see what the service does, you can have a look here:  https://codecov.io/github/JeroenMols/LandscapeVideoCamera?branch=master

**Comment by bhargavms** [comment]
Ah yes @kt3k talks about mentions in his repo. Thanks!
