### ISSUE TITLE
How can I use this in portrait mode instead?

### ISSUE THREAD

**Issue by franklinexpress** [JeroenMols/LandscapeVideoCamera#41]
I'm trying to see if there is a configuration param I can pass to make it Portrait, and even If I get portrait, the buttons would be on top I think. Any help?

God Speed.

**Comment by kevalpatel2106** [comment]
@franklinexpress I guess, there is no parameter for portrait mode. As the name of the project suggest. It only works in landscape.

**Comment by JeroenMols** [comment]
@franklinexpress this project explicitly focusses on landscape video. (portrait video really isn't convenient given all monitors/tvs are landscape)
You can always create a pull request and we'll consider merging.

**Comment by franklinexpress** [comment]
Sorry, should've read all the issues, saw some else ask this. Np, thanks.
