### ISSUE TITLE
Also, some of the phone before the camera recording, a preview of the stretch

### ISSUE THREAD

**Issue by rongdongliu** [JeroenMols/LandscapeVideoCamera#42]
Can provide vertical screen recording method?

Also, some of the phone before the camera recording, a preview of the stretch. (did you not meet the test at the time of the test)

I put the layout-land layout can be modified into a vertical screen after the vertical screen recording.

**Comment by wsclwps123** [comment]
你是横屏出现变形还是自己修改了源码竖屏出现了问题？

**Comment by JeroenMols** [comment]
Vertical screen recording is outside of the scope of this library.
