### ISSUE TITLE
No suitable constructor found on Version 1.2.2

### ISSUE THREAD

**Issue by tvaamorim** [JeroenMols/LandscapeVideoCamera#44]
int fileDuration = 10;
int filesize = CaptureConfiguration.NO_FILESIZE_LIMIT;
final CaptureConfiguration config = new CaptureConfiguration(800, 480, 1750000, fileDuration, filesize,true,true);

Trying to add the option to show the timer and to allow front camera.

`Error:(250, 49) error: no suitable constructor found for CaptureConfiguration(int,int,int,int,int,boolean,boolean)
constructor CaptureConfiguration.CaptureConfiguration() is not applicable
(actual and formal argument lists differ in length)
constructor CaptureConfiguration.CaptureConfiguration(CaptureResolution,CaptureQuality) is not applicable
(actual and formal argument lists differ in length)
constructor CaptureConfiguration.CaptureConfiguration(CaptureResolution,CaptureQuality,int,int,boolean) is not applicable
(actual and formal argument lists differ in length)
constructor CaptureConfiguration.CaptureConfiguration(CaptureResolution,CaptureQuality,int,int,boolean,boolean) is not applicable
(actual and formal argument lists differ in length)
constructor CaptureConfiguration.CaptureConfiguration(CaptureResolution,CaptureQuality,int,int) is not applicable
(actual and formal argument lists differ in length)
constructor CaptureConfiguration.CaptureConfiguration(int,int,int) is not applicable
(actual and formal argument lists differ in length)
constructor CaptureConfiguration.CaptureConfiguration(int,int,int,int,int) is not applicable
(actual and formal argument lists differ in length)
constructor CaptureConfiguration.CaptureConfiguration(Parcel) is not applicable
(actual and formal argument lists differ in length)`

What I am doing wrong?

**Comment by JeroenMols** [comment]
Version 1.3.0 now has a builder for CaptureConfigurations which should make it easier to use.
