### ISSUE TITLE
Support for setting desired FPS?

### ISSUE THREAD

**Issue by Dakor91** [JeroenMols/LandscapeVideoCamera#46]
Hi, do you have plans to add support for requesting a specific FPS for the video?

A fall back to lower FPS, if the desired FPS is not supported would be great as well.  (Or let the user change it in the Ui)

Thanks for your time!
Daniel

**Comment by kevalpatel2106** [comment]
@Dakor91 @JeroenMols I added the support for custom FPS in PR #47 .

**Comment by JeroenMols** [comment]
Added in v1.3.0
