### ISSUE TITLE
This app is not working on some device.

### ISSUE THREAD

**Issue by shaileshmulange** [JeroenMols/LandscapeVideoCamera#5]
I have tested this app on Samsung GT-S756, but it's not start the recording even preview is not captured.

**Comment by haogg** [comment]
Samsung Gt-M08 is also not working。The case is that It comes a weird preview screen likehttp://share.weiyun.com/3e9d6eaf8639784f2f13a8ce6b495c37  .It seems that the camera has stopped

**Comment by pauluhn** [comment]
CameraWrapper:getSupportedVideoSizes
params.getSupportedVideoSizes returns null
if null, return getSupportedPreviewSizes seems to work

**Comment by JeroenMols** [comment]
Hi @shaileshmulange and @haogg,

Could you please try out the solution from @pauluhn?
In case that works, I will add this to the library and create a new release.

Warm regards,
Jeroen

@pauluhn :+1: Thanks for suggesting a fix

**Comment by PutzDF** [comment]
@pauluhn or @JeroenMols  can you explain better how tofix this? I'm receiving this error on a galaxy nexus 
"Failed to find supported recording size - falling back to requested: 776x480"
The code that I'm using.
---
                int fileDuration = 10;
                int filesize = CaptureConfiguration.NO_FILESIZE_LIMIT;
                final CaptureConfiguration config = new CaptureConfiguration( 776,480,1750000, fileDuration, filesize);
                final Intent intent = new Intent(getActivity(), VideoCaptureActivity.class);
                intent.putExtra(VideoCaptureActivity.EXTRA_CAPTURE_CONFIGURATION, config);
                intent.putExtra(VideoCaptureActivity.EXTRA_OUTPUT_FILENAME, "video_created");
                startActivityForResult(intent, 152);

Thanks

**Comment by JeroenMols** [comment]
Hi @PutzDF,

I'v implemented a fallback to the preview video size when there is no hit for an actual video size. This should fix the original issue as reported by @shaileshmulange.

Can you retest to see if this also solves your issue?

**Comment by PutzDF** [comment]
@JeroenMols there is a new release with this fix? 1.1.1 ?

**Comment by JeroenMols** [comment]
@PutzDF Yes, just made a new release.
Sample app is also updated but still pending Google Play approval.

**Comment by mrzasan** [comment]
@JeroenMols   I tested this app on Samsung GT-S7568,preview is OK,but when click capture button,full screen being black and can not do other any operations,just only take off battery... Can you fix it?

**Comment by PutzDF** [comment]
@JeroenMols Gradle can't find the version 1.1.1, I will download it and test it later today. Thanks

**Comment by JeroenMols** [comment]
@tvaamorim mind the case sensitiveness of the Gradle dependency (I've updated the readme). It used to be all lower case, but JitPack changed something and now only the reference with upper cases is working.

**Comment by JeroenMols** [comment]
@mrzasan I don't have such a device to test on unfortunately. Can you download the entire repository and debug yourself to pinpoint the issue? I can help brainstorming about solutions.

**Comment by mrzasan** [comment]
Yes,of course.When i am free i will try it.

**Comment by JeroenMols** [comment]
@mrzasan did you have time to check this issue? it's been open for way to Ling now

**Comment by JeroenMols** [comment]
Closing this issue because no response from reporter

**Comment by YudizPankit** [comment]
I'm also having same issue in my Samsung S6.

**Comment by kevalpatel2106** [comment]
@YudizPankit I can confirm that this is working on my Galaxy S6.
