### ISSUE TITLE
LandscapeVideoCamera/1.3.0 build failed at jitpack

### ISSUE THREAD

**Issue by kevin-zqw** [JeroenMols/LandscapeVideoCamera#50]
Log [https://jitpack.io/com/github/JeroenMols/LandscapeVideoCamera/1.3.0/build.log](https://jitpack.io/com/github/JeroenMols/LandscapeVideoCamera/1.3.0/build.log)

The status was error, and I can't use gradle to build version 1.3.0

**Comment by Dakor91** [comment]
I also ran into this issue, Gradle kept complaining that it can't resolve the dependency, while 1.2.2 worked fine. 
For now i'm using the master-branch which should be identical with 1.3.0 for now:
`compile 'com.github.JeroenMols:LandscapeVideoCamera:master-SNAPSHOT'`

would be still great to have a working release 👍

**Comment by JeroenMols** [comment]
Can you give it another go? It is working for me now.

**Comment by kevin-zqw** [comment]
@JeroenMols Thanks, It is working now.

**Comment by JeroenMols** [comment]
The JitPack dependency casing has changed:

use: `compile 'com.github.jeroenmols:LandscapeVideoCamera:1.3.0'`

and not `compile 'com.github.JeroenMols:LandscapeVideoCamera:1.3.0`

I'll update the readme

**Comment by kevin-zqw** [comment]
I folk your repo for my own use, this library helped me a lot. Thanks so much.
