### ISSUE TITLE
hi,After recording the video will be black screen？

### ISSUE THREAD

**Issue by zhuxiaohao** [JeroenMols/LandscapeVideoCamera#51]
@JeroenMols  hi.This seems to be a bug,After recording the video will be black screen。

**Comment by JeroenMols** [comment]
Is there an actual file recorded on the sdcard of the phone/tablet? (size > 0)
Have you debugged step by step through it?

**Comment by zhuxiaohao** [comment]
感谢回复,这个问题是属于手机问题,手机太渣了,会导致这种问题.换其他手机测试就没有该问题.
