### ISSUE TITLE
Sync issue between Video and Audio

### ISSUE THREAD

**Issue by benjgorman** [JeroenMols/LandscapeVideoCamera#52]
I've been noticing a sync issue on recorded videos between the audio and video. Doesn't seem to depend on the FPS settings or the video size. Unsure if it's a bug or something I haven't set correctly?

**Comment by JeroenMols** [comment]
These things can be very hard to track down...
Have you tried experimenting with different video/audio encoders?

**Comment by JeroenMols** [comment]
Closing as nog update anymore
