### ISSUE TITLE
Question: Is there a way to only get the video file instead of saving it onto the device?

### ISSUE THREAD

**Issue by moses-lee** [JeroenMols/LandscapeVideoCamera#58]
Sorry I was pretty vague in my last question, but I was wondering whether the video taken had to be saved onto the device. I know I probably can just retrieve the video from the file and then delete the video, but wanted to know if there was a work around.

**Comment by JeroenMols** [comment]
That's not possible as video files are simply too large to pass around front one Activity to another.
