### ISSUE TITLE
Start again when limit is reached

### ISSUE THREAD

**Issue by john-peterson** [JeroenMols/LandscapeVideoCamera#7]
i wanna keep recording in 15 minutes pieces because in g+ " videos longer than 15 minutes count toward your storage limit". i haven't found an app that does this

**Comment by JeroenMols** [comment]
Hi @john-peterson,

LandscapeVideoCamera currently does not yet support that feature, but you are able to define a maximum capture duration (which you could set to 15 min).

I suggest you write your custom VideoCaptureActivity which adds this functionality on top of the VideoRecorder. There is no reason why that wouldn't work. (you can always submit your code using a pull request)

Good luck,
Jeroen

**Comment by john-peterson** [comment]
i found a road video recorder that does what i want https://play.google.com/store/apps/details?id=com.dailyroads.v
