### ISSUE TITLE
Max Duration not used in version 1.0.7

### ISSUE THREAD

**Issue by obj63mc** [JeroenMols/LandscapeVideoCamera#8]
Currently if you set the max duration in your capture configuration it is not being used.  The sample library is using version 1.0.6 of the library so something from that version to 1.07 either removed or broke this piece.  Trying to locate what specifically changed in that version history.

I set your sample to use 1.0.7 from maven locally and was able to replicate in that and my sample app.

Example configuration when using version 1.0.7 that fails - 

    final  CaptureConfiguration config = new CaptureConfiguration(CaptureResolution.RES_1080P, CaptureQuality.HIGH, 5, CaptureConfiguration.NO_FILESIZE_LIMIT);

**Comment by JeroenMols** [comment]
Your pull request #9 is integrated into the main branch, but this doesn't fix the issue.
More investigation will be needed to solve this

**Comment by obj63mc** [comment]
Still testing as well, trying to figure out why it won't take the setting.  Will let you know what I find out.

**Comment by obj63mc** [comment]
For some reason no matter what in terms of the camera profile whether using a completely custom one or inheriting, the duration wasn't respected.  Only setting it directly on the recorder object worked so not sure if this is just an android bug in general or problem with some phones but tested on a Nexus 7 and Moto X 2013.

**Comment by JeroenMols** [comment]
Verified the same here on my Nexus 5 and everything is working fine.
Fix should also be solid, because this was the way it was originally working before we moved to capture profiles.

You can get all changes in freshly released 1.1.0
